{
    'name': 'Caisse Management',
    'version': '18.0.1.0.1',
    'summary': 'Cash Advance and Expense Management System',
    'author': 'By Eric Mwaza (contact at ericmwaza@gmail.com)',
    'website': 'https://www.example.com',
    'license': 'AGPL-3',
    'category': 'Accounting/Finance',
    'depends': [
        'base',
        'account',
        'hr',
        'analytic',
    ],
    'data': [
        'security/caisse_security.xml',
        'data/caisse_data.xml',
        'views/caisse_report_wizard_views.xml',
        'views/caisse_config_views.xml',
        'views/caisse_request_type_views.xml',
        'views/caisse_request_views.xml',
        'views/caisse_disbursement_views.xml',
        'views/caisse_reconciliation_views.xml',
        'views/caisse_dashboard_views.xml',
        'reports/caisse_reports.xml',
        'views/caisse_menus.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}